// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dCBp3p2g2cgYAgGFEQRPSF
// Component: KBsl1BV-ZLdj
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: dCBp3p2g2cgYAgGFEQRPSF/projectcss
import sty from "./PlasmicSummaryCard.module.css"; // plasmic-import: KBsl1BV-ZLdj/css

createPlasmicElementProxy;

export const PlasmicSummaryCard__VariantProps = new Array("unnamedVariant");

export const PlasmicSummaryCard__ArgProps = new Array(
  "sumValue",
  "sumLabel",
  "onClick"
);

const $$ = {};

function PlasmicSummaryCard__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          sumValue: "3",
          sumLabel: "label"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "unnamedVariant",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.unnamedVariant
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
      onClick={args.onClick}
    >
      <Stack__
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__tnSVe)}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox__rjEe, {
            [sty.freeBoxunnamedVariant__rjEehFPp]: hasVariant(
              $state,
              "unnamedVariant",
              "unnamedVariant"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__itz9G,
              {
                [sty.textunnamedVariant__itz9GhFPp]: hasVariant(
                  $state,
                  "unnamedVariant",
                  "unnamedVariant"
                )
              }
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.sumValue;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "value";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        </div>
        <div
          className={classNames(projectcss.all, sty.freeBox__ggt4, {
            [sty.freeBoxunnamedVariant__ggt4HFPp]: hasVariant(
              $state,
              "unnamedVariant",
              "unnamedVariant"
            )
          })}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__dUrYc
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $props.sumLabel;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "label";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
        </div>
      </Stack__>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSummaryCard__ArgProps,
          internalVariantPropNames: PlasmicSummaryCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSummaryCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSummaryCard";
  } else {
    func.displayName = `PlasmicSummaryCard.${nodeName}`;
  }
  return func;
}

export const PlasmicSummaryCard = Object.assign(
  // Top-level PlasmicSummaryCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicSummaryCard
    internalVariantProps: PlasmicSummaryCard__VariantProps,
    internalArgProps: PlasmicSummaryCard__ArgProps
  }
);

export default PlasmicSummaryCard;
/* prettier-ignore-end */
