// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: dCBp3p2g2cgYAgGFEQRPSF
// Component: Xv-xnUJFB8Lu
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  initializeCodeComponentStates,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { RichCalendar } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-calendar";
import { calendarHelpers as RichCalendar_Helpers } from "@plasmicpkgs/plasmic-rich-components/skinny/rich-calendar";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: dCBp3p2g2cgYAgGFEQRPSF/projectcss
import sty from "./PlasmicCalenderTest.module.css"; // plasmic-import: Xv-xnUJFB8Lu/css

createPlasmicElementProxy;

export const PlasmicCalenderTest__VariantProps = new Array();

export const PlasmicCalenderTest__ArgProps = new Array();

const $$ = {};

function PlasmicCalenderTest__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "calendar.mode",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("mode", RichCalendar_Helpers)
      },
      {
        path: "calendar.selectedDate",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("selectedDate", RichCalendar_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (() => {
    const child$Props = {
      className: classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.calendar
      ),
      mode: generateStateValueProp($state, ["calendar", "mode"]),
      onChange: generateStateOnChangePropForCodeComponents(
        $state,
        "selectedDate",
        ["calendar", "selectedDate"],
        RichCalendar_Helpers
      ),
      onPanelChange: generateStateOnChangePropForCodeComponents(
        $state,
        "mode",
        ["calendar", "mode"],
        RichCalendar_Helpers
      ),
      value: generateStateValueProp($state, ["calendar", "selectedDate"])
    };
    initializeCodeComponentStates(
      $state,
      [
        {
          name: "mode",
          plasmicStateName: "calendar.mode"
        },
        {
          name: "selectedDate",
          plasmicStateName: "calendar.selectedDate"
        }
      ],

      [],
      RichCalendar_Helpers ?? {},
      child$Props
    );
    return (
      <RichCalendar
        data-plasmic-name={"calendar"}
        data-plasmic-override={overrides.calendar}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        {...child$Props}
      />
    );
  })();
}

const PlasmicDescendants = {
  calendar: ["calendar"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCalenderTest__ArgProps,
          internalVariantPropNames: PlasmicCalenderTest__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCalenderTest__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "calendar") {
    func.displayName = "PlasmicCalenderTest";
  } else {
    func.displayName = `PlasmicCalenderTest.${nodeName}`;
  }
  return func;
}

export const PlasmicCalenderTest = Object.assign(
  // Top-level PlasmicCalenderTest renders the root element
  makeNodeComponent("calendar"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicCalenderTest
    internalVariantProps: PlasmicCalenderTest__VariantProps,
    internalArgProps: PlasmicCalenderTest__ArgProps
  }
);

export default PlasmicCalenderTest;
/* prettier-ignore-end */
