// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicSelect3 } from "./plasmic/simply_maid_production/PlasmicSelect3";

function Select3_(props, ref) {
  // Use PlasmicSelect3 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicSelect3 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all Select3Props here, but feel free
  // to do whatever works for you.
  return <PlasmicSelect3 root={{ ref }} {...props} />;
}

const Select3 = React.forwardRef(Select3_);

export default Select3;
